name: Build and Publish RPE

on:
  push:
#    branches: [ "main" ]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-22.04,macos-latest,windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      MODE: ${{ matrix.os }}        

    steps:
      - uses: actions/checkout@v4
    
      - name: Setup Node.js ${{ matrix.os }}
        if: ${{ matrix.os != 'ubuntu-22.04' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.11 #if update this then also update in Dockerfile for centos

      - name: Setup Python
        if: ${{ matrix.os != 'ubuntu-22.04' }}
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.8 #if update this then also update in Dockerfile for centos

      - name: Login to the Container registry
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}          

      - name: Pull the CentOS image
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: docker pull ghcr.io/${{ github.repository_owner }}/rapid_power_estimator:centos7latest

      - name: Shell configuration on ${{ matrix.os }} 
        if: ${{ matrix.os != 'ubuntu-22.04' }}
        run: |
              node --version
              python3 -V

      - name: Shell configuration on centos 7
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: addnab/docker-run-action@v3
        with:
          shell: bash
          image: ghcr.io/${{ github.repository_owner }}/rapid_power_estimator:centos7latest
          run: |
                source /opt/rh/devtoolset-11/enable
                cmake --version
                node --version
                python3 -V
        
      - name: Install packages ${{ matrix.os }}
        if: ${{ matrix.os != 'ubuntu-22.04' }}
        run: |
            npm install
            python3 -m pip install -r requirements.txt

      - name: Install packages centos 7 & Run pytest
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: addnab/docker-run-action@v3
        with:
          shell: bash
          image: ghcr.io/${{ github.repository_owner }}/rapid_power_estimator:centos7latest
          options: -v ${{ github.workspace }}:/work
          run: |
                cd /work
                npm install
                python3 -m pip install -r requirements.txt
                python3 -m pytest

      - name: Run pytest
        if: ${{ matrix.os != 'ubuntu-22.04' }}
        run: python3 -m pytest


